* About

[[https://github.com/jakub-stastny/blog.engine/actions/workflows/test.yml][https://github.com/jakub-stastny/blog.engine/actions/workflows/test.yml/badge.svg]]

My blog engine written in Elm and Elm UI.

* Resources and community

This repository is only one of many packages that I wrote for my blog. For the overall architecture and documentation please see the [[https://github.com/jakub-stastny/blog][blog meta repo]]. That's also the place to [[https://github.com/jakub-stastny/blog/issues][raise any issues]] if you encounter any and to [[https://github.com/jakub-stastny/blog/discussions][discuss the project and ask questions]].

* Understanding the code base

/Where's all the source code?/

** Literate programming

In case you're wondering where are all the Elm files, you have to tangle code blocks from [[https://orgmode.org][Org mode]] files in =src= into actual Elm files using Org mode in Emacs.

Don't worry about it though – unless you want to set up the code locally, there is no need. Just read the Org mode files in the =src= directory, it contains well-documented code.

If you're curious why am I doing this, you can check my post on [[https://github.com/jakub-stastny/blog/blob/master/doc/literate-programming.org][literate programming]].

* Setup

See [[./.env/README.org][.env/README.org]] for literate DevOps instructions on setting the project.

Note that this setup is more of an extension of dotfiles (and requires specific initialisation code which I have in [[https://github.com/jakub-stastny/dotfiles][my dotfiles]]), it doesn't deal with installing Elm and the dependencies, for which I use [[https://github.com/jakub-stastny/docker-project-manager][docker-project-manager]].
