name: Elm tests

# Controls when the action will run.
on:
  push:
    branches: [ master ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
      
      - name: Run in $GITHUB_WORKSPACE
        run: cd $GITHUB_WORKSPACE
      
      - name: Install Node.js and Elm-test
        run: sudo apt-get install nodejs && sudo npm install -g elm-test
        
      - name: Emacs & Org mode
        run: sudo apt-get install emacs-nox && ./bin/install.el
      
      - name: Run Elm-test
        run: elm-test src/**/*Test.elm
